### ISSUE TITLE
Unable to install, aws-sdk version 0.9.6 not found

### ISSUE THREAD

**Issue by rex** [inspiredjw/winston-dynamodb#1]
Running `npm info aws-sdk` shows the following versions (abridged for sanity)

````
...
'0.9.4-pre.5',
'0.9.5-pre.6',
'0.9.6-pre.7',
'0.9.7-pre.8',
'0.9.8-pre.9',
'0.9.9-pre.10',
'1.0.0'
...
````

What is the issue with the later versions of `aws-sdk`? Are there breakages? In its current state this npm module is completely uninstallable.

How can I help?

**Comment by anddimario** [comment]
Hi, it seems that i've the same error.
Thanks for your time.
Best regards

**Comment by inspiredjw** [comment]
resolved
