### ISSUE TITLE
Add support for localhost

### ISSUE THREAD

**Issue by srobinet** [inspiredjw/winston-dynamodb#7]
We use a local DynamoDb instance for testing.  It would be great if the options could be expanded to include setting a custom endpoint, e.g. http://localhost:8000.

**Comment by raphaelmun** [comment]
I've created a PR with a change to support this: https://github.com/inspiredjw/winston-dynamodb/pull/8
Hopefully it gets accepted, but in the meantime you could work off of this change.

**Comment by jwchang0206** [comment]
Merged #8
